--- !ruby/object:Jumpstart::Configuration
application_name: RepTrack
business_name: RepTrack
domain: example.com
support_email: jack@workdoneperfect.com
default_from_email: jack@workdoneperfect.com
business_address: ''
background_job_processor: sidekiq
email_provider: ''
personal_accounts: false
solargraph: false
register_with_account: false
apns: false
fcm: false
